# -*- coding: utf-8 -*-
"""Data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rjTGsE_yqIm6x11oCPH38UlWH33ZWtQG

Cell 1-Mount Google Drive
"""

# Connect Google Drive to Colab so we can access our project folder
from google.colab import drive
drive.mount('/content/drive')

## Cell 2 — Find your folder
import os

# This prints everything in your Drive root — find your project folder name here
os.listdir('/content/drive/My Drive/')

## Cell 3 — Import libraries
import pandas as pd
import numpy as np
print('Libraries loaded successfully')
print(f'Pandas version: {pd.__version__}')

# encoding='latin-1' → needed because UK product names have special characters
# without this Python throws a UnicodeDecodeError
FILE_PATH = '/content/drive/My Drive/CustomerBehaviourProject/Dataset/online_retail_II.csv'
df = pd.read_csv(FILE_PATH, encoding='latin-1')
print(f'Loaded successfully!')
print(f'Shape: {df.shape[0]:,} rows x {df.shape[1]} columns')
df.head()

# Initial data assessment — always do this before touching anything
# dtypes   → tells us if any columns have wrong data types
# isnull() → tells us which columns have missing values and how many
# describe() → catches negatives, zeros, or suspicious outliers in numbers
print('======= COLUMN TYPES =======')
print(df.dtypes)

print('\n======= MISSING VALUES =======')
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
print(pd.DataFrame({
    'missing count': missing,
    'missing %': missing_pct
})[missing > 0])

print('\n======= BASIC STATS =======')
df[['Quantity', 'Price']].describe()

# Save row count BEFORE any cleaning starts
# We need this at the end to calculate how many rows were removed in total
# Once we start cleaning, df gets overwritten — this number would be lost
original_count = len(df)
print(f'Original row count saved: {original_count:,}')

## standardise column names
###**Why:** SQL and Python both prefer `snake_case`. Spaces in column names cause errors in SQL queries.
###This converts `Customer ID` → `customer_id`, `Invoice Date` → `invoice_date`, etc.

df.columns = (
    df.columns
    .str.strip()        # remove accidental spaces
    .str.lower()        # all lowercase
    .str.replace(' ', '_')  # spaces to underscores
)
print('Column names after cleaning:')
print(df.columns.tolist())

## Cell 8 — Remove cancelled orders
#**Why:** Invoices starting with `'C'` are cancellations. They have negative quantities.
#If we keep them, our revenue totals will be wrong and customer spend will be understated.
#In corporate analytics, cancelled orders are usually analysed separately — not mixed into sales data.
cancelled_mask = df['invoice'].astype(str).str.startswith('C')
cancelled_count = cancelled_mask.sum()

print(f'Cancelled orders found: {cancelled_count:,} ({cancelled_count/len(df)*100:.1f}% of data)')

df = df[~cancelled_mask]
print(f'Rows remaining: {len(df):,}')

##Removing Rows with no customer ID because if we dont have it we can't consider it in customer's Journey.
missing_cust = df['customer_id'].isnull().sum()
print(f'Rows missing Customer ID: {missing_cust:,} ({missing_cust/len(df)*100:.1f}%)')

df = df.dropna(subset=['customer_id'])
print(f'Rows remaining: {len(df):,}')

# quantity or price of zero or below has no business meaning in sales data
# likely data entry errors or internal test records
# & means AND → both conditions must pass for a row to be kept
bad_qty   = (df['quantity'] <= 0).sum()
bad_price = (df['price'] <= 0).sum()

print(f'Rows with quantity <= 0: {bad_qty:,}')
print(f'Rows with price <= 0:    {bad_price:,}')

df = df[(df['quantity'] > 0) & (df['price'] > 0)]
print(f'Rows remaining: {len(df):,}')
# Step 1: check quantity column — is every value greater than zero? (True/False for each row)
# Step 2: check price column — is every value greater than zero? (True/False for each row)
# Step 3: & means AND — only keep rows where BOTH checks pass
# Step 4: save the filtered result back into df, overwriting the old one

# invoicedate loaded as a string → convert to datetime so we can group by month,
#                                   calculate recency, and do any time-based analysis
# customer_id loaded as float (because of earlier missing values) → convert to int
#                                   for cleaner SQL queries and joins
df['invoicedate'] = pd.to_datetime(df['invoicedate'])
df['customer_id'] = df['customer_id'].astype(int)

print('Data types after fixing:')
print(df.dtypes)

# Check row wise — is this entire row an identical copy of another row?
# Duplicate rows double-count transactions and inflate all metrics
# .duplicated() → returns True for every row that is an exact copy
# .sum()        → counts all the True values = total duplicate count
dupes = df.duplicated().sum()
print(f'Duplicate rows found: {dupes:,}')

df = df.drop_duplicates()
print(f'Rows remaining: {len(df):,}')

# revenue = quantity x price → most commonly queried metric in retail analytics
# adding it now means SQL queries can use it directly without recalculating
# .round(2) → keep to 2 decimal places (pence/cents)
df['revenue'] = (df['quantity'] * df['price']).round(2)

print(f'Revenue column added.')
print(f'Total revenue in clean dataset: £{df["revenue"].sum():,.2f}')
df[['invoice', 'customer_id', 'quantity', 'price', 'revenue']].head()

# final_count = current size of df after all cleaning steps
# removed = original_count (Cell 6) - final_count → total rows dropped
# this summary documents every decision made — goes straight into the README
# >10 in formatting → right aligns numbers so output looks like a proper report
final_count  = len(df)
removed      = original_count - final_count

print('============================================')
print('           CLEANING SUMMARY')
print('============================================')
print(f'  Original rows       : {original_count:>10,}')
print(f'  Rows removed        : {removed:>10,}  ({removed/original_count*100:.1f}%)')
print(f'  Final clean rows    : {final_count:>10,}')
print(f'  Columns             : {df.shape[1]}')
print(f'  Date range          : {df["invoicedate"].min().date()} to {df["invoicedate"].max().date()}')
print(f'  Unique customers    : {df["customer_id"].nunique():,}')
print(f'  Unique products     : {df["stockcode"].nunique():,}')
print(f'  Countries           : {df["country"].nunique()}')
print(f'  Total revenue       : £{df["revenue"].sum():,.2f}')
print('============================================')

# Export the cleaned dataframe as a new CSV file back to Google Drive
# This is the file we load into MySQL Workbench for all SQL analysis
# index=False → don't write the row numbers into the file, they're not real data
OUTPUT_PATH = '/content/drive/My Drive/CustomerBehaviourProject/Dataset/online_retail_clean.csv'

df.to_csv(OUTPUT_PATH, index=False)

print(f'Exported clean file to: {OUTPUT_PATH}')
print(f'Final shape: {df.shape}')